CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.FileOperations Class Reference
ce103_hw4_library_lib.FileOperations Class Reference
Static Public Member Functions
static byte[] readBlock (int count, int blocksize, String path) throws IOException
static boolean appendBlockCounter (byte[] data, String path) throws IOException
static boolean appendBlock (byte[] data, String path) throws IOException
static boolean appendBlock2 (byte[] data, int offset, int blocksize, String path) throws IOException
static boolean updateBlock (byte[] data, int offset, int blocksize, String path) throws IOException
static boolean deleteBlock (int count, int blocksize, String path) throws IOException
static boolean deleteBlock2 (int blockSize, int offset, String path)
Member Function Documentation
appendBlock()
static boolean ce103_hw4_library_lib.FileOperations.appendBlock (byte[] data, String path) throws IOException static
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine(), ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2(), ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
appendBlock2()
static boolean ce103_hw4_library_lib.FileOperations.appendBlock2 (byte[] data, int offset, int blocksize, String path) throws IOException static
appendBlockCounter()
static boolean ce103_hw4_library_lib.FileOperations.appendBlockCounter (byte[] data, String path) throws IOException static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), and ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter().
deleteBlock()
static boolean ce103_hw4_library_lib.FileOperations.deleteBlock (int count, int blocksize, String path) throws IOException static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
deleteBlock2()
static boolean ce103_hw4_library_lib.FileOperations.deleteBlock2 (int blockSize, int offset, String path) static
References ce103_hw4_library_lib.DataOperations.StringToByteArray().
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2().
readBlock()
static byte[] ce103_hw4_library_lib.FileOperations.readBlock (int count, int blocksize, String path) throws IOException static
Referenced by ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.UnitTest.testCustomerUpdate().
updateBlock()
static boolean ce103_hw4_library_lib.FileOperations.updateBlock (byte[] data, int offset, int blocksize, String path) throws IOException static
Referenced by ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/FileOperations.java