CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.MedicineFeature Class Reference
ce103_hw4_library_lib.MedicineFeature Class Reference
Public Member Functions
final int getId ()
final void setId (int value)
final String getname_s ()
final void setname_s (String value)
final int getRack ()
final void setRack (int value)
final int getCabnit ()
final void setCabnit (int value)
final String getCompany ()
final void setCompany (String value)
final String getMedicine ()
final void setMedicine (String value)
final int getUnitcost ()
final void setUnitcost (int value)
final int getSalecost ()
final void setSalecost (int value)
final int getQuantity ()
final void setQuantity (int value)
final String getMgf_date ()
final void setMgf_date (String value)
final String getExp_date ()
final void setExp_date (String value)
final String getName ()
final void setName (String value)
Static Public Member Functions
static byte[] MedicineToByteArrayBlock (MedicineFeature Medicine)
static MedicineFeature ByteArrayBlockToMedicineCounter (byte[] byteArray) throws IOException
static MedicineFeature ByteArrayBlockToMedicine (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int name_s_MAX_LENGTH = 100
static final int rack_MAX_LENGTH = 4
static final int cabnit_MAX_LENGTH = 4
static final int company_NAME_MAX_LENGTH = 100
static final int Medicine_NAME_MAX_LENGTH = 100
static final int unitcost_MAX_LENGTH = 10
static final int salecost_MAX_LENGTH = 10
static final int quantity_MAX_LENGTH = 10
static final int mgf_date_LENGTH = 30
static final int exp_date_LENGTH = 30
static final int Medicine_DATA_BLOCK_SIZE
static final int SaleMedicine_DATA_BLOCK_SIZE = ID_LENGTH + Medicine_NAME_MAX_LENGTH
Private Attributes
int _id
String _name_s
int _rack
int _cabnit
String _company
String _Medicine
int _unitcost
int _salecost
int _quantity
String _mgf_date
String _exp_date
String _name
Member Function Documentation
ByteArrayBlockToMedicine()
static MedicineFeature ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine (byte[] byteArray) static
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.DataOperations.byteArrayToString(), ce103_hw4_library_lib.MedicineFeature.cabnit_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.company_NAME_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.exp_date_LENGTH, ce103_hw4_library_lib.MedicineFeature.getId(), ce103_hw4_library_lib.MedicineFeature.ID_LENGTH, ce103_hw4_library_lib.MedicineFeature.Medicine_DATA_BLOCK_SIZE, ce103_hw4_library_lib.MedicineFeature.Medicine_NAME_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.mgf_date_LENGTH, ce103_hw4_library_lib.MedicineFeature.name_s_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.quantity_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.rack_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.salecost_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.setCabnit(), ce103_hw4_library_lib.MedicineFeature.setCompany(), ce103_hw4_library_lib.MedicineFeature.setExp_date(), ce103_hw4_library_lib.MedicineFeature.setId(), ce103_hw4_library_lib.MedicineFeature.setMedicine(), ce103_hw4_library_lib.MedicineFeature.setMgf_date(), ce103_hw4_library_lib.MedicineFeature.setname_s(), ce103_hw4_library_lib.MedicineFeature.setQuantity(), ce103_hw4_library_lib.MedicineFeature.setRack(), ce103_hw4_library_lib.MedicineFeature.setSalecost(), ce103_hw4_library_lib.MedicineFeature.setUnitcost(), and ce103_hw4_library_lib.MedicineFeature.unitcost_MAX_LENGTH.
Referenced by ce103_hw4_library_app.App.main().
ByteArrayBlockToMedicineCounter()
static MedicineFeature ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter (byte[] byteArray) throws IOException static
References ce103_hw4_library_lib.FileOperations.appendBlockCounter(), ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.MedicineFeature.getId(), ce103_hw4_library_lib.MedicineFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), and ce103_hw4_library_lib.MedicineFeature.setId().
getCabnit()
final int ce103_hw4_library_lib.MedicineFeature.getCabnit ()
References ce103_hw4_library_lib.MedicineFeature._cabnit.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getCompany()
final String ce103_hw4_library_lib.MedicineFeature.getCompany ()
References ce103_hw4_library_lib.MedicineFeature._company.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getExp_date()
final String ce103_hw4_library_lib.MedicineFeature.getExp_date ()
References ce103_hw4_library_lib.MedicineFeature._exp_date.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getId()
final int ce103_hw4_library_lib.MedicineFeature.getId ()
References ce103_hw4_library_lib.MedicineFeature._id.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getMedicine()
final String ce103_hw4_library_lib.MedicineFeature.getMedicine ()
References ce103_hw4_library_lib.MedicineFeature._Medicine.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getMgf_date()
final String ce103_hw4_library_lib.MedicineFeature.getMgf_date ()
References ce103_hw4_library_lib.MedicineFeature._mgf_date.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getName()
final String ce103_hw4_library_lib.MedicineFeature.getName ()
References ce103_hw4_library_lib.MedicineFeature._name.
getname_s()
final String ce103_hw4_library_lib.MedicineFeature.getname_s ()
References ce103_hw4_library_lib.MedicineFeature._name_s.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getQuantity()
final int ce103_hw4_library_lib.MedicineFeature.getQuantity ()
References ce103_hw4_library_lib.MedicineFeature._quantity.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getRack()
final int ce103_hw4_library_lib.MedicineFeature.getRack ()
References ce103_hw4_library_lib.MedicineFeature._rack.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getSalecost()
final int ce103_hw4_library_lib.MedicineFeature.getSalecost ()
References ce103_hw4_library_lib.MedicineFeature._salecost.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
getUnitcost()
final int ce103_hw4_library_lib.MedicineFeature.getUnitcost ()
References ce103_hw4_library_lib.MedicineFeature._unitcost.
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
MedicineToByteArrayBlock()
static byte[] ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock (MedicineFeature Medicine) static
References ce103_hw4_library_lib.MedicineFeature.cabnit_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.company_NAME_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.exp_date_LENGTH, ce103_hw4_library_lib.MedicineFeature.getCabnit(), ce103_hw4_library_lib.MedicineFeature.getCompany(), ce103_hw4_library_lib.MedicineFeature.getExp_date(), ce103_hw4_library_lib.MedicineFeature.getId(), ce103_hw4_library_lib.MedicineFeature.getMedicine(), ce103_hw4_library_lib.MedicineFeature.getMgf_date(), ce103_hw4_library_lib.MedicineFeature.getname_s(), ce103_hw4_library_lib.MedicineFeature.getQuantity(), ce103_hw4_library_lib.MedicineFeature.getRack(), ce103_hw4_library_lib.MedicineFeature.getSalecost(), ce103_hw4_library_lib.MedicineFeature.getUnitcost(), ce103_hw4_library_lib.MedicineFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.MedicineFeature.Medicine_DATA_BLOCK_SIZE, ce103_hw4_library_lib.MedicineFeature.Medicine_NAME_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.mgf_date_LENGTH, ce103_hw4_library_lib.MedicineFeature.name_s_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.quantity_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.rack_MAX_LENGTH, ce103_hw4_library_lib.MedicineFeature.salecost_MAX_LENGTH, ce103_hw4_library_lib.DataOperations.StringToByteArray(), and ce103_hw4_library_lib.MedicineFeature.unitcost_MAX_LENGTH.
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setCabnit()
final void ce103_hw4_library_lib.MedicineFeature.setCabnit (int value)
References ce103_hw4_library_lib.MedicineFeature._cabnit.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2().
setCompany()
final void ce103_hw4_library_lib.MedicineFeature.setCompany (String value)
References ce103_hw4_library_lib.MedicineFeature._company.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setExp_date()
final void ce103_hw4_library_lib.MedicineFeature.setExp_date (String value)
References ce103_hw4_library_lib.MedicineFeature._exp_date.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setId()
final void ce103_hw4_library_lib.MedicineFeature.setId (int value)
References ce103_hw4_library_lib.MedicineFeature._id.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setMedicine()
final void ce103_hw4_library_lib.MedicineFeature.setMedicine (String value)
References ce103_hw4_library_lib.MedicineFeature._Medicine.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setMgf_date()
final void ce103_hw4_library_lib.MedicineFeature.setMgf_date (String value)
References ce103_hw4_library_lib.MedicineFeature._mgf_date.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setName()
final void ce103_hw4_library_lib.MedicineFeature.setName (String value)
References ce103_hw4_library_lib.MedicineFeature._name.
setname_s()
final void ce103_hw4_library_lib.MedicineFeature.setname_s (String value)
References ce103_hw4_library_lib.MedicineFeature._name_s.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setQuantity()
final void ce103_hw4_library_lib.MedicineFeature.setQuantity (int value)
References ce103_hw4_library_lib.MedicineFeature._quantity.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setRack()
final void ce103_hw4_library_lib.MedicineFeature.setRack (int value)
References ce103_hw4_library_lib.MedicineFeature._rack.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2().
setSalecost()
final void ce103_hw4_library_lib.MedicineFeature.setSalecost (int value)
References ce103_hw4_library_lib.MedicineFeature._salecost.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
setUnitcost()
final void ce103_hw4_library_lib.MedicineFeature.setUnitcost (int value)
References ce103_hw4_library_lib.MedicineFeature._unitcost.
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock().
Member Data Documentation
_cabnit
int ce103_hw4_library_lib.MedicineFeature._cabnit private
Referenced by ce103_hw4_library_lib.MedicineFeature.getCabnit(), and ce103_hw4_library_lib.MedicineFeature.setCabnit().
_company
String ce103_hw4_library_lib.MedicineFeature._company private
Referenced by ce103_hw4_library_lib.MedicineFeature.getCompany(), and ce103_hw4_library_lib.MedicineFeature.setCompany().
_exp_date
String ce103_hw4_library_lib.MedicineFeature._exp_date private
Referenced by ce103_hw4_library_lib.MedicineFeature.getExp_date(), and ce103_hw4_library_lib.MedicineFeature.setExp_date().
_id
int ce103_hw4_library_lib.MedicineFeature._id private
Referenced by ce103_hw4_library_lib.MedicineFeature.getId(), and ce103_hw4_library_lib.MedicineFeature.setId().
_Medicine
String ce103_hw4_library_lib.MedicineFeature._Medicine private
Referenced by ce103_hw4_library_lib.MedicineFeature.getMedicine(), and ce103_hw4_library_lib.MedicineFeature.setMedicine().
_mgf_date
String ce103_hw4_library_lib.MedicineFeature._mgf_date private
Referenced by ce103_hw4_library_lib.MedicineFeature.getMgf_date(), and ce103_hw4_library_lib.MedicineFeature.setMgf_date().
_name
String ce103_hw4_library_lib.MedicineFeature._name private
Referenced by ce103_hw4_library_lib.MedicineFeature.getName(), and ce103_hw4_library_lib.MedicineFeature.setName().
_name_s
String ce103_hw4_library_lib.MedicineFeature._name_s private
Referenced by ce103_hw4_library_lib.MedicineFeature.getname_s(), and ce103_hw4_library_lib.MedicineFeature.setname_s().
_quantity
int ce103_hw4_library_lib.MedicineFeature._quantity private
Referenced by ce103_hw4_library_lib.MedicineFeature.getQuantity(), and ce103_hw4_library_lib.MedicineFeature.setQuantity().
_rack
int ce103_hw4_library_lib.MedicineFeature._rack private
Referenced by ce103_hw4_library_lib.MedicineFeature.getRack(), and ce103_hw4_library_lib.MedicineFeature.setRack().
_salecost
int ce103_hw4_library_lib.MedicineFeature._salecost private
Referenced by ce103_hw4_library_lib.MedicineFeature.getSalecost(), and ce103_hw4_library_lib.MedicineFeature.setSalecost().
_unitcost
int ce103_hw4_library_lib.MedicineFeature._unitcost private
Referenced by ce103_hw4_library_lib.MedicineFeature.getUnitcost(), and ce103_hw4_library_lib.MedicineFeature.setUnitcost().
cabnit_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.cabnit_MAX_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
company_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.company_NAME_MAX_LENGTH = 100 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
exp_date_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.exp_date_LENGTH = 30 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
ID_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.ID_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
Medicine_DATA_BLOCK_SIZE
final int ce103_hw4_library_lib.MedicineFeature.Medicine_DATA_BLOCK_SIZE static
Initial value:
= ID_LENGTH + rack_MAX_LENGTH + cabnit_MAX_LENGTH + name_s_MAX_LENGTH
    + company_NAME_MAX_LENGTH + Medicine_NAME_MAX_LENGTH + unitcost_MAX_LENGTH + salecost_MAX_LENGTH + quantity_MAX_LENGTH + mgf_date_LENGTH
    + exp_date_LENGTH
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
Medicine_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.Medicine_NAME_MAX_LENGTH = 100 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
mgf_date_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.mgf_date_LENGTH = 30 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
name_s_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.name_s_MAX_LENGTH = 100 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
quantity_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.quantity_MAX_LENGTH = 10 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
rack_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.rack_MAX_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
salecost_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.salecost_MAX_LENGTH = 10 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
SaleMedicine_DATA_BLOCK_SIZE
final int ce103_hw4_library_lib.MedicineFeature.SaleMedicine_DATA_BLOCK_SIZE = ID_LENGTH + Medicine_NAME_MAX_LENGTH static
unitcost_MAX_LENGTH
final int ce103_hw4_library_lib.MedicineFeature.unitcost_MAX_LENGTH = 10 static
Referenced by ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/MedicineFeature.java