CE103 Algorithms and Programming I HW4: ce103_hw4_library_app.App Class Reference
ce103_hw4_library_app.App Class Reference
Static Public Member Functions
static void main (String[] args) throws IOException, InterruptedException
Static Public Attributes
static int ID
static String ID_Control
static String Name
static String City
static int Contact_No
static String Contact_No_C
static String Email_ID
static int Rack
static String Rack_C
static int Cabnit
static String Cabnit_C
static String Company
static String Medicine
static int Unit_Cost
static String Unit_Cost_C
static int Sale_Cost
static String Sale_Cost_C
static int Quantity
static String Quantity_C
static String Mgf_Date
static String Exp_Date
Member Function Documentation
main()
static void ce103_hw4_library_app.App.main (String[] args) throws IOException, InterruptedException static
SEARCH
SEARCH
SEARCH
About
REPORT
Bill
Exit
References ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2(), ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.Cabnit, ce103_hw4_library_app.App.Cabnit_C, ce103_hw4_library_app.App.City, ce103_hw4_library_app.App.Company, ce103_hw4_library_app.App.Contact_No, ce103_hw4_library_app.App.Contact_No_C, ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE, ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.FileOperations.deleteBlock2(), ce103_hw4_library_app.App.Email_ID, ce103_hw4_library_app.App.Exp_Date, ce103_hw4_library_lib.MedicineFeature.getCabnit(), ce103_hw4_library_lib.CustomerFeature.getcity(), ce103_hw4_library_lib.SupplierFeature.getcity(), ce103_hw4_library_lib.MedicineFeature.getCompany(), ce103_hw4_library_lib.CustomerFeature.getcontact_no(), ce103_hw4_library_lib.SupplierFeature.getcontact_no(), ce103_hw4_library_lib.CustomerFeature.getemail(), ce103_hw4_library_lib.SupplierFeature.getemail(), ce103_hw4_library_lib.MedicineFeature.getExp_date(), ce103_hw4_library_lib.CustomerFeature.getId(), ce103_hw4_library_lib.MedicineFeature.getId(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.MedicineFeature.getMedicine(), ce103_hw4_library_lib.MedicineFeature.getMgf_date(), ce103_hw4_library_lib.CustomerFeature.getname_s(), ce103_hw4_library_lib.MedicineFeature.getname_s(), ce103_hw4_library_lib.SupplierFeature.getname_s(), ce103_hw4_library_lib.MedicineFeature.getQuantity(), ce103_hw4_library_lib.MedicineFeature.getRack(), ce103_hw4_library_lib.MedicineFeature.getSalecost(), ce103_hw4_library_lib.MedicineFeature.getUnitcost(), ce103_hw4_library_app.App.ID, ce103_hw4_library_app.App.ID_Control, ce103_hw4_library_app.App.Medicine, ce103_hw4_library_lib.MedicineFeature.Medicine_DATA_BLOCK_SIZE, ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock(), ce103_hw4_library_app.App.Mgf_Date, ce103_hw4_library_app.App.Name, ce103_hw4_library_app.App.Quantity, ce103_hw4_library_app.App.Quantity_C, ce103_hw4_library_app.App.Rack, ce103_hw4_library_app.App.Rack_C, ce103_hw4_library_lib.FileOperations.readBlock(), ce103_hw4_library_app.App.Sale_Cost, ce103_hw4_library_app.App.Sale_Cost_C, ce103_hw4_library_lib.MedicineFeature.setCabnit(), ce103_hw4_library_lib.CustomerFeature.setcity(), ce103_hw4_library_lib.SupplierFeature.setcity(), ce103_hw4_library_lib.MedicineFeature.setCompany(), ce103_hw4_library_lib.CustomerFeature.setcontact_no(), ce103_hw4_library_lib.SupplierFeature.setcontact_no(), ce103_hw4_library_lib.CustomerFeature.setemail(), ce103_hw4_library_lib.SupplierFeature.setemail(), ce103_hw4_library_lib.MedicineFeature.setExp_date(), ce103_hw4_library_lib.CustomerFeature.setId(), ce103_hw4_library_lib.MedicineFeature.setId(), ce103_hw4_library_lib.SupplierFeature.setId(), ce103_hw4_library_lib.MedicineFeature.setMedicine(), ce103_hw4_library_lib.MedicineFeature.setMgf_date(), ce103_hw4_library_lib.CustomerFeature.setname_s(), ce103_hw4_library_lib.MedicineFeature.setname_s(), ce103_hw4_library_lib.SupplierFeature.setname_s(), ce103_hw4_library_lib.MedicineFeature.setQuantity(), ce103_hw4_library_lib.MedicineFeature.setRack(), ce103_hw4_library_lib.MedicineFeature.setSalecost(), ce103_hw4_library_lib.MedicineFeature.setUnitcost(), ce103_hw4_library_lib.SupplierFeature.Supplier_DATA_BLOCK_SIZE, ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), ce103_hw4_library_app.App.Unit_Cost, ce103_hw4_library_app.App.Unit_Cost_C, and ce103_hw4_library_lib.FileOperations.updateBlock().
Member Data Documentation
Cabnit
int ce103_hw4_library_app.App.Cabnit static
Referenced by ce103_hw4_library_app.App.main().
Cabnit_C
String ce103_hw4_library_app.App.Cabnit_C static
Referenced by ce103_hw4_library_app.App.main().
City
String ce103_hw4_library_app.App.City static
Referenced by ce103_hw4_library_app.App.main().
Company
String ce103_hw4_library_app.App.Company static
Referenced by ce103_hw4_library_app.App.main().
Contact_No
int ce103_hw4_library_app.App.Contact_No static
Referenced by ce103_hw4_library_app.App.main().
Contact_No_C
String ce103_hw4_library_app.App.Contact_No_C static
Referenced by ce103_hw4_library_app.App.main().
Email_ID
String ce103_hw4_library_app.App.Email_ID static
Referenced by ce103_hw4_library_app.App.main().
Exp_Date
String ce103_hw4_library_app.App.Exp_Date static
Referenced by ce103_hw4_library_app.App.main().
ID
int ce103_hw4_library_app.App.ID static
Referenced by ce103_hw4_library_app.App.main().
ID_Control
String ce103_hw4_library_app.App.ID_Control static
Referenced by ce103_hw4_library_app.App.main().
Medicine
String ce103_hw4_library_app.App.Medicine static
Referenced by ce103_hw4_library_app.App.main().
Mgf_Date
String ce103_hw4_library_app.App.Mgf_Date static
Referenced by ce103_hw4_library_app.App.main().
Name
String ce103_hw4_library_app.App.Name static
Referenced by ce103_hw4_library_app.App.main().
Quantity
int ce103_hw4_library_app.App.Quantity static
Referenced by ce103_hw4_library_app.App.main().
Quantity_C
String ce103_hw4_library_app.App.Quantity_C static
Referenced by ce103_hw4_library_app.App.main().
Rack
int ce103_hw4_library_app.App.Rack static
Referenced by ce103_hw4_library_app.App.main().
Rack_C
String ce103_hw4_library_app.App.Rack_C static
Referenced by ce103_hw4_library_app.App.main().
Sale_Cost
int ce103_hw4_library_app.App.Sale_Cost static
Referenced by ce103_hw4_library_app.App.main().
Sale_Cost_C
String ce103_hw4_library_app.App.Sale_Cost_C static
Referenced by ce103_hw4_library_app.App.main().
Unit_Cost
int ce103_hw4_library_app.App.Unit_Cost static
Referenced by ce103_hw4_library_app.App.main().
Unit_Cost_C
String ce103_hw4_library_app.App.Unit_Cost_C static
Referenced by ce103_hw4_library_app.App.main().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_app/App.java