CE103 Algorithms and Programming I HW4: ce103_hw4_library_cmd.UnitTest Class Reference
ce103_hw4_library_cmd.UnitTest Class Reference
Public Member Functions
void testSupplierCreationAndFileWriting () throws IOException
void testSupplierCreation () throws IOException
void testGetInt ()
void testSetAndGetId ()
void testSetAndGetName ()
Member Function Documentation
testGetInt()
void ce103_hw4_library_cmd.UnitTest.testGetInt ()
References ce103_hw4_library_lib.DataOperations.GetInt().
testSetAndGetId()
void ce103_hw4_library_cmd.UnitTest.testSetAndGetId ()
References ce103_hw4_library_lib.CustomerFeature.getId(), and ce103_hw4_library_lib.CustomerFeature.setId().
testSetAndGetName()
void ce103_hw4_library_cmd.UnitTest.testSetAndGetName ()
References ce103_hw4_library_lib.CustomerFeature.getname_s(), and ce103_hw4_library_lib.CustomerFeature.setname_s().
testSupplierCreation()
void ce103_hw4_library_cmd.UnitTest.testSupplierCreation () throws IOException
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.SupplierFeature.getcity(), ce103_hw4_library_lib.SupplierFeature.getcontact_no(), ce103_hw4_library_lib.SupplierFeature.getemail(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.SupplierFeature.getname_s(), ce103_hw4_library_lib.SupplierFeature.setcity(), ce103_hw4_library_lib.SupplierFeature.setcontact_no(), ce103_hw4_library_lib.SupplierFeature.setemail(), ce103_hw4_library_lib.SupplierFeature.setId(), ce103_hw4_library_lib.SupplierFeature.setname_s(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
testSupplierCreationAndFileWriting()
void ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting () throws IOException
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.SupplierFeature.setcity(), ce103_hw4_library_lib.SupplierFeature.setcontact_no(), ce103_hw4_library_lib.SupplierFeature.setemail(), ce103_hw4_library_lib.SupplierFeature.setId(), ce103_hw4_library_lib.SupplierFeature.setname_s(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_cmd/UnitTest.java