CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.SaleMedicineFeature Class Reference
ce103_hw4_library_lib.SaleMedicineFeature Class Reference
Public Member Functions
final int getCustomerId ()
final void setCustomerId (int value)
final int getMedicineId ()
final void setMedicineId (int value)
final int getMedicineQuantity ()
final void setMedicineQuantity (int value)
final String getSaleDate ()
final void setSaleDate (String value)
Static Public Member Functions
static byte[] BookToByteArrayBlock (SaleMedicineFeature sale)
static SaleMedicineFeature ByteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int CUSTOMER_ID_MAX_LENGTH = 4
static final int MEDICINE_ID_LENGTH = 4
static final int SALE_DATA_BLOCK_SIZE = CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH
Private Attributes
int _customerId
int _medicineId
int _medicineQuantity
String _saleDate
Member Function Documentation
BookToByteArrayBlock()
static byte[] ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock (SaleMedicineFeature sale) static
References ce103_hw4_library_lib.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH, ce103_hw4_library_lib.SaleMedicineFeature.getCustomerId(), ce103_hw4_library_lib.SaleMedicineFeature.getMedicineId(), ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.SaleMedicineFeature.MEDICINE_ID_LENGTH, and ce103_hw4_library_lib.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine(), and ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2().
ByteArrayBlockToBook()
static SaleMedicineFeature ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook (byte[] byteArray) static
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH, ce103_hw4_library_lib.SaleMedicineFeature.getMedicineId(), ce103_hw4_library_lib.SaleMedicineFeature.MEDICINE_ID_LENGTH, ce103_hw4_library_lib.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE, ce103_hw4_library_lib.SaleMedicineFeature.setCustomerId(), and ce103_hw4_library_lib.SaleMedicineFeature.setMedicineId().
getCustomerId()
final int ce103_hw4_library_lib.SaleMedicineFeature.getCustomerId ()
References ce103_hw4_library_lib.SaleMedicineFeature._customerId.
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock().
getMedicineId()
final int ce103_hw4_library_lib.SaleMedicineFeature.getMedicineId ()
References ce103_hw4_library_lib.SaleMedicineFeature._medicineId.
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
getMedicineQuantity()
final int ce103_hw4_library_lib.SaleMedicineFeature.getMedicineQuantity ()
References ce103_hw4_library_lib.SaleMedicineFeature._medicineQuantity.
getSaleDate()
final String ce103_hw4_library_lib.SaleMedicineFeature.getSaleDate ()
References ce103_hw4_library_lib.SaleMedicineFeature._saleDate.
setCustomerId()
final void ce103_hw4_library_lib.SaleMedicineFeature.setCustomerId (int value)
References ce103_hw4_library_lib.SaleMedicineFeature._customerId.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine(), ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
setMedicineId()
final void ce103_hw4_library_lib.SaleMedicineFeature.setMedicineId (int value)
References ce103_hw4_library_lib.SaleMedicineFeature._medicineId.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine(), ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
setMedicineQuantity()
final void ce103_hw4_library_lib.SaleMedicineFeature.setMedicineQuantity (int value)
References ce103_hw4_library_lib.SaleMedicineFeature._medicineQuantity.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine().
setSaleDate()
final void ce103_hw4_library_lib.SaleMedicineFeature.setSaleDate (String value)
References ce103_hw4_library_lib.SaleMedicineFeature._saleDate.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine().
Member Data Documentation
_customerId
int ce103_hw4_library_lib.SaleMedicineFeature._customerId private
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.getCustomerId(), and ce103_hw4_library_lib.SaleMedicineFeature.setCustomerId().
_medicineId
int ce103_hw4_library_lib.SaleMedicineFeature._medicineId private
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.getMedicineId(), and ce103_hw4_library_lib.SaleMedicineFeature.setMedicineId().
_medicineQuantity
int ce103_hw4_library_lib.SaleMedicineFeature._medicineQuantity private
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.getMedicineQuantity(), and ce103_hw4_library_lib.SaleMedicineFeature.setMedicineQuantity().
_saleDate
String ce103_hw4_library_lib.SaleMedicineFeature._saleDate private
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.getSaleDate(), and ce103_hw4_library_lib.SaleMedicineFeature.setSaleDate().
CUSTOMER_ID_MAX_LENGTH
final int ce103_hw4_library_lib.SaleMedicineFeature.CUSTOMER_ID_MAX_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
MEDICINE_ID_LENGTH
final int ce103_hw4_library_lib.SaleMedicineFeature.MEDICINE_ID_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
SALE_DATA_BLOCK_SIZE
final int ce103_hw4_library_lib.SaleMedicineFeature.SALE_DATA_BLOCK_SIZE = CUSTOMER_ID_MAX_LENGTH + MEDICINE_ID_LENGTH static
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), and ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/SaleMedicineFeature.java