CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.CustomerFeature Class Reference
ce103_hw4_library_lib.CustomerFeature Class Reference
Public Member Functions
final int getId ()
final void setId (int value)
final String getname_s ()
final void setname_s (String value)
final String getcity ()
final void setcity (String value)
final int getcontact_no ()
final void setcontact_no (int value)
final String getemail ()
final void setemail (String value)
final String getName ()
final void setName (String value)
final String getReturnDate ()
final void setReturnDate (String value)
final String getDate ()
final void setDate (String value)
Static Public Member Functions
static byte[] CustomerToByteArrayBlock (CustomerFeature Customer)
static CustomerFeature ByteArrayBlockToCustomerCounter (byte[] byteArray) throws IOException
static CustomerFeature ByteArrayBlockToCustomer (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int name_s_MAX_LENGTH = 50
static final int city_MAX_LENGTH = 50
static final int contact_no_NAME_MAX_LENGTH = 20
static final int email_NAME_MAX_LENGTH = 50
static final int Customer_DATA_BLOCK_SIZE = ID_LENGTH + city_MAX_LENGTH + contact_no_NAME_MAX_LENGTH + name_s_MAX_LENGTH + email_NAME_MAX_LENGTH
Private Attributes
int _id
String _name_s
String _city
int _contact_no
String _email
String _name
String _return_date
String _date
Member Function Documentation
ByteArrayBlockToCustomer()
static CustomerFeature ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer (byte[] byteArray) static
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.DataOperations.byteArrayToString(), ce103_hw4_library_lib.CustomerFeature.city_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.contact_no_NAME_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE, ce103_hw4_library_lib.CustomerFeature.email_NAME_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.getId(), ce103_hw4_library_lib.CustomerFeature.ID_LENGTH, ce103_hw4_library_lib.CustomerFeature.name_s_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.setcity(), ce103_hw4_library_lib.CustomerFeature.setcontact_no(), ce103_hw4_library_lib.CustomerFeature.setemail(), ce103_hw4_library_lib.CustomerFeature.setId(), and ce103_hw4_library_lib.CustomerFeature.setname_s().
Referenced by ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.UnitTest.testCustomerUpdate().
ByteArrayBlockToCustomerCounter()
static CustomerFeature ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter (byte[] byteArray) throws IOException static
References ce103_hw4_library_lib.FileOperations.appendBlockCounter(), ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.CustomerFeature.getId(), ce103_hw4_library_lib.CustomerFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), and ce103_hw4_library_lib.CustomerFeature.setId().
CustomerToByteArrayBlock()
static byte[] ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock (CustomerFeature Customer) static
References ce103_hw4_library_lib.CustomerFeature.city_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.contact_no_NAME_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE, ce103_hw4_library_lib.CustomerFeature.email_NAME_MAX_LENGTH, ce103_hw4_library_lib.CustomerFeature.getcity(), ce103_hw4_library_lib.CustomerFeature.getcontact_no(), ce103_hw4_library_lib.CustomerFeature.getemail(), ce103_hw4_library_lib.CustomerFeature.getId(), ce103_hw4_library_lib.CustomerFeature.getname_s(), ce103_hw4_library_lib.CustomerFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.CustomerFeature.name_s_MAX_LENGTH, and ce103_hw4_library_lib.DataOperations.StringToByteArray().
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
getcity()
final String ce103_hw4_library_lib.CustomerFeature.getcity ()
References ce103_hw4_library_lib.CustomerFeature._city.
Referenced by ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), and ce103_hw4_library_app.App.main().
getcontact_no()
final int ce103_hw4_library_lib.CustomerFeature.getcontact_no ()
References ce103_hw4_library_lib.CustomerFeature._contact_no.
Referenced by ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), and ce103_hw4_library_app.App.main().
getDate()
final String ce103_hw4_library_lib.CustomerFeature.getDate ()
References ce103_hw4_library_lib.CustomerFeature._date.
getemail()
final String ce103_hw4_library_lib.CustomerFeature.getemail ()
References ce103_hw4_library_lib.CustomerFeature._email.
Referenced by ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), and ce103_hw4_library_app.App.main().
getId()
final int ce103_hw4_library_lib.CustomerFeature.getId ()
References ce103_hw4_library_lib.CustomerFeature._id.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_cmd.UnitTest.testSetAndGetId().
getName()
final String ce103_hw4_library_lib.CustomerFeature.getName ()
References ce103_hw4_library_lib.CustomerFeature._name.
getname_s()
final String ce103_hw4_library_lib.CustomerFeature.getname_s ()
References ce103_hw4_library_lib.CustomerFeature._name_s.
Referenced by ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_cmd.UnitTest.testSetAndGetName().
getReturnDate()
final String ce103_hw4_library_lib.CustomerFeature.getReturnDate ()
References ce103_hw4_library_lib.CustomerFeature._return_date.
setcity()
final void ce103_hw4_library_lib.CustomerFeature.setcity (String value)
References ce103_hw4_library_lib.CustomerFeature._city.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
setcontact_no()
final void ce103_hw4_library_lib.CustomerFeature.setcontact_no (int value)
References ce103_hw4_library_lib.CustomerFeature._contact_no.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), and ce103_hw4_library_lib.UnitTest.testCustomerUpdate().
setDate()
final void ce103_hw4_library_lib.CustomerFeature.setDate (String value)
References ce103_hw4_library_lib.CustomerFeature._date.
setemail()
final void ce103_hw4_library_lib.CustomerFeature.setemail (String value)
References ce103_hw4_library_lib.CustomerFeature._email.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
setId()
final void ce103_hw4_library_lib.CustomerFeature.setId (int value)
References ce103_hw4_library_lib.CustomerFeature._id.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), ce103_hw4_library_lib.UnitTest.testPrintCustomers(), and ce103_hw4_library_cmd.UnitTest.testSetAndGetId().
setName()
final void ce103_hw4_library_lib.CustomerFeature.setName (String value)
References ce103_hw4_library_lib.CustomerFeature._name.
setname_s()
final void ce103_hw4_library_lib.CustomerFeature.setname_s (String value)
References ce103_hw4_library_lib.CustomerFeature._name_s.
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerAddition(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), ce103_hw4_library_lib.UnitTest.testPrintCustomers(), and ce103_hw4_library_cmd.UnitTest.testSetAndGetName().
setReturnDate()
final void ce103_hw4_library_lib.CustomerFeature.setReturnDate (String value)
References ce103_hw4_library_lib.CustomerFeature._return_date.
Member Data Documentation
_city
String ce103_hw4_library_lib.CustomerFeature._city private
Referenced by ce103_hw4_library_lib.CustomerFeature.getcity(), and ce103_hw4_library_lib.CustomerFeature.setcity().
_contact_no
int ce103_hw4_library_lib.CustomerFeature._contact_no private
Referenced by ce103_hw4_library_lib.CustomerFeature.getcontact_no(), and ce103_hw4_library_lib.CustomerFeature.setcontact_no().
_date
String ce103_hw4_library_lib.CustomerFeature._date private
Referenced by ce103_hw4_library_lib.CustomerFeature.getDate(), and ce103_hw4_library_lib.CustomerFeature.setDate().
_email
String ce103_hw4_library_lib.CustomerFeature._email private
Referenced by ce103_hw4_library_lib.CustomerFeature.getemail(), and ce103_hw4_library_lib.CustomerFeature.setemail().
_id
int ce103_hw4_library_lib.CustomerFeature._id private
Referenced by ce103_hw4_library_lib.CustomerFeature.getId(), and ce103_hw4_library_lib.CustomerFeature.setId().
_name
String ce103_hw4_library_lib.CustomerFeature._name private
Referenced by ce103_hw4_library_lib.CustomerFeature.getName(), and ce103_hw4_library_lib.CustomerFeature.setName().
_name_s
String ce103_hw4_library_lib.CustomerFeature._name_s private
Referenced by ce103_hw4_library_lib.CustomerFeature.getname_s(), and ce103_hw4_library_lib.CustomerFeature.setname_s().
_return_date
String ce103_hw4_library_lib.CustomerFeature._return_date private
Referenced by ce103_hw4_library_lib.CustomerFeature.getReturnDate(), and ce103_hw4_library_lib.CustomerFeature.setReturnDate().
city_MAX_LENGTH
final int ce103_hw4_library_lib.CustomerFeature.city_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), and ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock().
contact_no_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.CustomerFeature.contact_no_NAME_MAX_LENGTH = 20 static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), and ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock().
Customer_DATA_BLOCK_SIZE
final int ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE = ID_LENGTH + city_MAX_LENGTH + contact_no_NAME_MAX_LENGTH + name_s_MAX_LENGTH + email_NAME_MAX_LENGTH static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.UnitTest.testCustomerUpdate(), and ce103_hw4_library_lib.UnitTest.testPrintCustomers().
email_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.CustomerFeature.email_NAME_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), and ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock().
ID_LENGTH
final int ce103_hw4_library_lib.CustomerFeature.ID_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), and ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock().
name_s_MAX_LENGTH
final int ce103_hw4_library_lib.CustomerFeature.name_s_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), and ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/CustomerFeature.java