CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.MainFunctions Class Reference
ce103_hw4_library_lib.MainFunctions Class Reference
Public Member Functions
void controlFile (String path, String filename) throws IOException
final void AddSupplier (int ID, String Name, String City, int Contact_No, String Email_ID, String path) throws IOException
final void DecreaseBook (int amount) throws IOException
final int DecreaseBook2 (int amount) throws IOException
Static Public Member Functions
static final void ControlFile (String FileName) throws IOException
static final void AddSaleMedicine (int MedicineId, int CustomerId, int MedicineQuantity, String SaleDate) throws IOException
static final void AddSaleMedicine2 (int MedicineId, int CustomerId) throws IOException
Member Function Documentation
AddSaleMedicine()
static final void ce103_hw4_library_lib.MainFunctions.AddSaleMedicine (int MedicineId, int CustomerId, int MedicineQuantity, String SaleDate) throws IOException static
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), ce103_hw4_library_lib.MainFunctions.ControlFile(), ce103_hw4_library_lib.SaleMedicineFeature.setCustomerId(), ce103_hw4_library_lib.SaleMedicineFeature.setMedicineId(), ce103_hw4_library_lib.SaleMedicineFeature.setMedicineQuantity(), and ce103_hw4_library_lib.SaleMedicineFeature.setSaleDate().
AddSaleMedicine2()
static final void ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2 (int MedicineId, int CustomerId) throws IOException static
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), ce103_hw4_library_lib.MainFunctions.ControlFile(), ce103_hw4_library_lib.SaleMedicineFeature.setCustomerId(), and ce103_hw4_library_lib.SaleMedicineFeature.setMedicineId().
Referenced by ce103_hw4_library_app.App.main().
AddSupplier()
final void ce103_hw4_library_lib.MainFunctions.AddSupplier (int ID, String Name, String City, int Contact_No, String Email_ID, String path) throws IOException
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.SupplierFeature.setcity(), ce103_hw4_library_lib.SupplierFeature.setcontact_no(), ce103_hw4_library_lib.SupplierFeature.setemail(), ce103_hw4_library_lib.SupplierFeature.setId(), ce103_hw4_library_lib.SupplierFeature.setname_s(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
Referenced by ce103_hw4_library_app.App.main().
ControlFile()
static final void ce103_hw4_library_lib.MainFunctions.ControlFile (String FileName) throws IOException static
Referenced by ce103_hw4_library_lib.MainFunctions.AddSaleMedicine(), ce103_hw4_library_lib.MainFunctions.AddSaleMedicine2(), and ce103_hw4_library_lib.UnitTest.testControlFile().
controlFile()
void ce103_hw4_library_lib.MainFunctions.controlFile (String path, String filename) throws IOException
DecreaseBook()
final void ce103_hw4_library_lib.MainFunctions.DecreaseBook (int amount) throws IOException
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.FileOperations.readBlock(), ce103_hw4_library_lib.SupplierFeature.setId(), and ce103_hw4_library_lib.FileOperations.updateBlock().
DecreaseBook2()
final int ce103_hw4_library_lib.MainFunctions.DecreaseBook2 (int amount) throws IOException
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.FileOperations.readBlock(), ce103_hw4_library_lib.SupplierFeature.setId(), and ce103_hw4_library_lib.FileOperations.updateBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/MainFunctions.java