CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.UnitTest Class Reference
ce103_hw4_library_lib.UnitTest Class Reference
Public Member Functions
void testControlFile () throws IOException
void testPrintCustomers () throws IOException
void testMedicineToByteArrayBlock ()
void testAddSaleMedicine2 () throws IOException
void testCustomerAddition () throws IOException
void testCustomerUpdate () throws IOException
Member Function Documentation
testAddSaleMedicine2()
void ce103_hw4_library_lib.UnitTest.testAddSaleMedicine2 () throws IOException
References ce103_hw4_library_lib.FileOperations.deleteBlock2(), ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock(), ce103_hw4_library_lib.MedicineFeature.setCabnit(), ce103_hw4_library_lib.MedicineFeature.setCompany(), ce103_hw4_library_lib.MedicineFeature.setExp_date(), ce103_hw4_library_lib.MedicineFeature.setId(), ce103_hw4_library_lib.MedicineFeature.setMedicine(), ce103_hw4_library_lib.MedicineFeature.setMgf_date(), ce103_hw4_library_lib.MedicineFeature.setname_s(), ce103_hw4_library_lib.MedicineFeature.setQuantity(), ce103_hw4_library_lib.MedicineFeature.setRack(), ce103_hw4_library_lib.MedicineFeature.setSalecost(), and ce103_hw4_library_lib.MedicineFeature.setUnitcost().
testControlFile()
void ce103_hw4_library_lib.UnitTest.testControlFile () throws IOException
References ce103_hw4_library_lib.MainFunctions.ControlFile().
testCustomerAddition()
void ce103_hw4_library_lib.UnitTest.testCustomerAddition () throws IOException
References ce103_hw4_library_lib.FileOperations.appendBlock(), ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.CustomerFeature.setcity(), ce103_hw4_library_lib.CustomerFeature.setcontact_no(), ce103_hw4_library_lib.CustomerFeature.setemail(), ce103_hw4_library_lib.CustomerFeature.setId(), and ce103_hw4_library_lib.CustomerFeature.setname_s().
testCustomerUpdate()
void ce103_hw4_library_lib.UnitTest.testCustomerUpdate () throws IOException
References ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE, ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.FileOperations.readBlock(), ce103_hw4_library_lib.CustomerFeature.setcity(), ce103_hw4_library_lib.CustomerFeature.setcontact_no(), ce103_hw4_library_lib.CustomerFeature.setemail(), ce103_hw4_library_lib.CustomerFeature.setId(), ce103_hw4_library_lib.CustomerFeature.setname_s(), and ce103_hw4_library_lib.FileOperations.updateBlock().
testMedicineToByteArrayBlock()
void ce103_hw4_library_lib.UnitTest.testMedicineToByteArrayBlock ()
References ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock(), ce103_hw4_library_lib.MedicineFeature.setCompany(), ce103_hw4_library_lib.MedicineFeature.setExp_date(), ce103_hw4_library_lib.MedicineFeature.setId(), ce103_hw4_library_lib.MedicineFeature.setMedicine(), ce103_hw4_library_lib.MedicineFeature.setMgf_date(), ce103_hw4_library_lib.MedicineFeature.setname_s(), ce103_hw4_library_lib.MedicineFeature.setQuantity(), ce103_hw4_library_lib.MedicineFeature.setSalecost(), and ce103_hw4_library_lib.MedicineFeature.setUnitcost().
testPrintCustomers()
void ce103_hw4_library_lib.UnitTest.testPrintCustomers () throws IOException
References ce103_hw4_library_lib.CustomerFeature.Customer_DATA_BLOCK_SIZE, ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.CustomerFeature.setcity(), ce103_hw4_library_lib.CustomerFeature.setemail(), ce103_hw4_library_lib.CustomerFeature.setId(), ce103_hw4_library_lib.CustomerFeature.setname_s(), and ce103_hw4_library_lib.FileOperations.updateBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/UnitTest.java