CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.DataOperations Class Reference
ce103_hw4_library_lib.DataOperations Class Reference
Static Public Member Functions
static int[] ToByte (String hexString)
static String ToHex (byte[] arr)
static boolean IsHex (String str)
static int GetInt (byte[] data, int offset, int length)
static String ToAscii (String hexString)
static int byteArrayToInteger (byte[] byteArray)
static byte[] integerToByteArray (int value)
static byte[] StringToByteArray (String data)
static String byteArrayToString (byte[] byteArray)
Member Function Documentation
byteArrayToInteger()
static int ce103_hw4_library_lib.DataOperations.byteArrayToInteger (byte[] byteArray) static
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.ByteArrayBlockToBook(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), ce103_hw4_library_lib.MainFunctions.DecreaseBook(), and ce103_hw4_library_lib.MainFunctions.DecreaseBook2().
byteArrayToString()
static String ce103_hw4_library_lib.DataOperations.byteArrayToString (byte[] byteArray) static
Referenced by ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomer(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicine(), and ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier().
GetInt()
static int ce103_hw4_library_lib.DataOperations.GetInt (byte[] data, int offset, int length) static
Referenced by ce103_hw4_library_cmd.UnitTest.testGetInt().
integerToByteArray()
static byte[] ce103_hw4_library_lib.DataOperations.integerToByteArray (int value) static
Referenced by ce103_hw4_library_lib.SaleMedicineFeature.BookToByteArrayBlock(), ce103_hw4_library_lib.CustomerFeature.ByteArrayBlockToCustomerCounter(), ce103_hw4_library_lib.MedicineFeature.ByteArrayBlockToMedicineCounter(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
IsHex()
static boolean ce103_hw4_library_lib.DataOperations.IsHex (String str) static
References ce103_hw4_library_lib.DataOperations.ToByte().
StringToByteArray()
static byte[] ce103_hw4_library_lib.DataOperations.StringToByteArray (String data) static
Referenced by ce103_hw4_library_lib.CustomerFeature.CustomerToByteArrayBlock(), ce103_hw4_library_lib.FileOperations.deleteBlock2(), ce103_hw4_library_lib.MedicineFeature.MedicineToByteArrayBlock(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
ToAscii()
static String ce103_hw4_library_lib.DataOperations.ToAscii (String hexString) static
ToByte()
static int[] ce103_hw4_library_lib.DataOperations.ToByte (String hexString) static
Referenced by ce103_hw4_library_lib.DataOperations.IsHex().
ToHex()
static String ce103_hw4_library_lib.DataOperations.ToHex (byte[] arr) static
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/DataOperations.java