CE103 Algorithms and Programming I HW4: ce103_hw4_library_lib.SupplierFeature Class Reference
ce103_hw4_library_lib.SupplierFeature Class Reference
Public Member Functions
final int getId ()
final void setId (int value)
final String getname_s ()
final void setname_s (String value)
final String getcity ()
final void setcity (String value)
final int getcontact_no ()
final void setcontact_no (int value)
final String getemail ()
final void setemail (String value)
Static Public Member Functions
static byte[] SupplierToByteArrayBlock (SupplierFeature Supplier)
static SupplierFeature ByteArrayBlockToSupplierCounter (byte[] byteArray) throws IOException
static SupplierFeature ByteArrayBlockToSupplier (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int name_s_MAX_LENGTH = 50
static final int city_MAX_LENGTH = 50
static final int contact_no_NAME_MAX_LENGTH = 20
static final int email_NAME_MAX_LENGTH = 50
static final int Supplier_DATA_BLOCK_SIZE = ID_LENGTH + city_MAX_LENGTH + contact_no_NAME_MAX_LENGTH + name_s_MAX_LENGTH + email_NAME_MAX_LENGTH
static final int Name_Lenght = 30
static final int Return_Date_Lenght = 20
static final int Date_Lenght = 30
static final int Borrow_Data_Block_Size = Name_Lenght + Return_Date_Lenght + Date_Lenght + ID_LENGTH
Private Attributes
int _id
String _name_s
String _city
int _contact_no
String _email
Member Function Documentation
ByteArrayBlockToSupplier()
static SupplierFeature ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier (byte[] byteArray) static
References ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.DataOperations.byteArrayToString(), ce103_hw4_library_lib.SupplierFeature.city_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.contact_no_NAME_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.email_NAME_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.SupplierFeature.ID_LENGTH, ce103_hw4_library_lib.SupplierFeature.name_s_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.setcity(), ce103_hw4_library_lib.SupplierFeature.setcontact_no(), ce103_hw4_library_lib.SupplierFeature.setemail(), ce103_hw4_library_lib.SupplierFeature.setId(), ce103_hw4_library_lib.SupplierFeature.setname_s(), and ce103_hw4_library_lib.SupplierFeature.Supplier_DATA_BLOCK_SIZE.
Referenced by ce103_hw4_library_app.App.main().
ByteArrayBlockToSupplierCounter()
static SupplierFeature ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter (byte[] byteArray) throws IOException static
References ce103_hw4_library_lib.FileOperations.appendBlockCounter(), ce103_hw4_library_lib.DataOperations.byteArrayToInteger(), ce103_hw4_library_lib.FileOperations.deleteBlock(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.SupplierFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), and ce103_hw4_library_lib.SupplierFeature.setId().
getcity()
final String ce103_hw4_library_lib.SupplierFeature.getcity ()
References ce103_hw4_library_lib.SupplierFeature._city.
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreation().
getcontact_no()
final int ce103_hw4_library_lib.SupplierFeature.getcontact_no ()
References ce103_hw4_library_lib.SupplierFeature._contact_no.
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreation().
getemail()
final String ce103_hw4_library_lib.SupplierFeature.getemail ()
References ce103_hw4_library_lib.SupplierFeature._email.
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreation().
getId()
final int ce103_hw4_library_lib.SupplierFeature.getId ()
References ce103_hw4_library_lib.SupplierFeature._id.
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreation().
getname_s()
final String ce103_hw4_library_lib.SupplierFeature.getname_s ()
References ce103_hw4_library_lib.SupplierFeature._name_s.
Referenced by ce103_hw4_library_app.App.main(), ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreation().
setcity()
final void ce103_hw4_library_lib.SupplierFeature.setcity (String value)
References ce103_hw4_library_lib.SupplierFeature._city.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
setcontact_no()
final void ce103_hw4_library_lib.SupplierFeature.setcontact_no (int value)
References ce103_hw4_library_lib.SupplierFeature._contact_no.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
setemail()
final void ce103_hw4_library_lib.SupplierFeature.setemail (String value)
References ce103_hw4_library_lib.SupplierFeature._email.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
setId()
final void ce103_hw4_library_lib.SupplierFeature.setId (int value)
References ce103_hw4_library_lib.SupplierFeature._id.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), ce103_hw4_library_lib.MainFunctions.DecreaseBook(), ce103_hw4_library_lib.MainFunctions.DecreaseBook2(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
setname_s()
final void ce103_hw4_library_lib.SupplierFeature.setname_s (String value)
References ce103_hw4_library_lib.SupplierFeature._name_s.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
SupplierToByteArrayBlock()
static byte[] ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock (SupplierFeature Supplier) static
References ce103_hw4_library_lib.SupplierFeature.city_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.contact_no_NAME_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.email_NAME_MAX_LENGTH, ce103_hw4_library_lib.SupplierFeature.getcity(), ce103_hw4_library_lib.SupplierFeature.getcontact_no(), ce103_hw4_library_lib.SupplierFeature.getemail(), ce103_hw4_library_lib.SupplierFeature.getId(), ce103_hw4_library_lib.SupplierFeature.getname_s(), ce103_hw4_library_lib.SupplierFeature.ID_LENGTH, ce103_hw4_library_lib.DataOperations.integerToByteArray(), ce103_hw4_library_lib.SupplierFeature.name_s_MAX_LENGTH, ce103_hw4_library_lib.DataOperations.StringToByteArray(), and ce103_hw4_library_lib.SupplierFeature.Supplier_DATA_BLOCK_SIZE.
Referenced by ce103_hw4_library_lib.MainFunctions.AddSupplier(), ce103_hw4_library_app.App.main(), ce103_hw4_library_cmd.UnitTest.testSupplierCreation(), and ce103_hw4_library_cmd.UnitTest.testSupplierCreationAndFileWriting().
Member Data Documentation
_city
String ce103_hw4_library_lib.SupplierFeature._city private
Referenced by ce103_hw4_library_lib.SupplierFeature.getcity(), and ce103_hw4_library_lib.SupplierFeature.setcity().
_contact_no
int ce103_hw4_library_lib.SupplierFeature._contact_no private
Referenced by ce103_hw4_library_lib.SupplierFeature.getcontact_no(), and ce103_hw4_library_lib.SupplierFeature.setcontact_no().
_email
String ce103_hw4_library_lib.SupplierFeature._email private
Referenced by ce103_hw4_library_lib.SupplierFeature.getemail(), and ce103_hw4_library_lib.SupplierFeature.setemail().
_id
int ce103_hw4_library_lib.SupplierFeature._id private
Referenced by ce103_hw4_library_lib.SupplierFeature.getId(), and ce103_hw4_library_lib.SupplierFeature.setId().
_name_s
String ce103_hw4_library_lib.SupplierFeature._name_s private
Referenced by ce103_hw4_library_lib.SupplierFeature.getname_s(), and ce103_hw4_library_lib.SupplierFeature.setname_s().
Borrow_Data_Block_Size
final int ce103_hw4_library_lib.SupplierFeature.Borrow_Data_Block_Size = Name_Lenght + Return_Date_Lenght + Date_Lenght + ID_LENGTH static
city_MAX_LENGTH
final int ce103_hw4_library_lib.SupplierFeature.city_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
contact_no_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.SupplierFeature.contact_no_NAME_MAX_LENGTH = 20 static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
Date_Lenght
final int ce103_hw4_library_lib.SupplierFeature.Date_Lenght = 30 static
email_NAME_MAX_LENGTH
final int ce103_hw4_library_lib.SupplierFeature.email_NAME_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
ID_LENGTH
final int ce103_hw4_library_lib.SupplierFeature.ID_LENGTH = 4 static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplierCounter(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
Name_Lenght
final int ce103_hw4_library_lib.SupplierFeature.Name_Lenght = 30 static
name_s_MAX_LENGTH
final int ce103_hw4_library_lib.SupplierFeature.name_s_MAX_LENGTH = 50 static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
Return_Date_Lenght
final int ce103_hw4_library_lib.SupplierFeature.Return_Date_Lenght = 20 static
Supplier_DATA_BLOCK_SIZE
final int ce103_hw4_library_lib.SupplierFeature.Supplier_DATA_BLOCK_SIZE = ID_LENGTH + city_MAX_LENGTH + contact_no_NAME_MAX_LENGTH + name_s_MAX_LENGTH + email_NAME_MAX_LENGTH static
Referenced by ce103_hw4_library_lib.SupplierFeature.ByteArrayBlockToSupplier(), ce103_hw4_library_app.App.main(), and ce103_hw4_library_lib.SupplierFeature.SupplierToByteArrayBlock().
The documentation for this class was generated from the following file:
C:/Users/Gokay/Desktop/newww/ce103-hw4-gokay-dervisoglu/medical_store/ce103_hw4_medical_store_lib/SupplierFeature.java